export const WebhookEnvironmentVariables = {
  WEBHOOK_SECRET_ARN: 'WEBHOOK_SECRET_ARN',
  EVENT_BUS_NAME: 'EVENT_BUS_NAME',
  IDEMPOTENCY_TABLE_NAME: 'IDEMPOTENCY_TABLE_NAME',
  PAYLOAD_BUCKET_NAME: 'PAYLOAD_BUCKET_NAME',
} as const;

export const EVENTBRIDGE_MAX_DETAIL_BYTES = 200_000;
