import { Operation } from '@aws-smithy/server-common';
import {
  ClientSideError,
  GetAppTokenInput,
  GetAppTokenOutput,
  ServerSideError,
} from '@scottschreckengaust/app-framework-for-github-apps-on-aws-ssdk';
import { getAppTokenImpl } from './getAppToken';
import { VisibleError } from '../../error';

/**
 * Operation handler generated by Smithy that retrieves a GitHub App token using the given App ID.
 *
 * This function performs validation on the input, looks up the app data from
 * App table (provided via context), and returns a signed token.
 * ---
 * @param input The request input which must include appId.
 * @param _context Context passed in from the framework, must include `tableName` for DynamoDB access.
 * @returns The signed app token as a GetAppTokenOutput object.
 */
export const getAppTokenOperation: Operation<
  GetAppTokenInput,
  GetAppTokenOutput,
  { tableName: string }
> = async (input, _context): Promise<GetAppTokenOutput> => {
  console.log('getAppTokenOperation', input);
  const { appId } = input as { appId: number };
  const tableName = _context.tableName;
  try {
    const appToken = await getAppTokenImpl({
      appId,
      tableName: tableName,
    });
    return {
      appId,
      appToken: appToken.appToken,
      expirationTime: appToken.expiration_time,
    };
  } catch (error) {
    if (error instanceof VisibleError) {
      throw new ClientSideError({ message: `Invalid Request: ${error}` });
    }
    console.error(error);
    throw new ServerSideError({ message: 'Internal Server Error' });
  }
};
